services:
  app:
    image: ghcr.io/ipuppyyt/docuseal:latest
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - ./storage:/data/docuseal
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RAILS_LOG_TO_STDOUT=true
